backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "sections"
    label: "Sections"
    folder: "sections"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "ID",
          name: "id",
          hint: "Used for navigation",
          widget: "string",
        }
      - {
          label: "Order",
          hint: "Display order",
          name: "date",
          widget: "datetime",
        }
      - {
          label: "Show Title",
          name: "showTitle",
          hint: "Whether or not to show title at top of section",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Show Form",
          name: "showForm",
          hint: "Whether or not to show RSVP form",
          widget: "boolean",
          default: false,
          retuired: false,
        }
      - {
          label: "Background Image",
          name: "background-image",
          widget: "image",
          default: "",
        }
      - { label: "Body", name: "body", widget: "markdown" }
